### ISSUE TITLE
Icon placement on multiple pages

### ISSUE THREAD

**Issue by pinhead84** [chdemko/pandoc-latex-tip#10]
Thank you for this nice little addition to Pandoc.

I have a question regarding icon placement. My PDF document contains multiple pages. On each even page number the icon is placed on the right side - even if `position: left` is specified. On the other hand if i set `position: right`, the icon is placed on the left side on even page numbers.

Is this intended behaviour - or a bug?

It's kind of strange, because your *pandoc-latex-admonition* filter does not behave like this. A combination of *pandoc-latex-admonition* and *pandoc-latex-tip* leads to kind of inconsistent results.

**Comment by chdemko** [comment]
Could you please post an example file and the command you ran?

**Comment by pinhead84** [comment]
> Could you please post an example file and the command you ran?

Of course. I'm attaching an example markdown file ([`test.txt`](https://github.com/chdemko/pandoc-latex-tip/files/2863108/test.txt), because GitHub doesn't allow me to upload files with md extension) and a PDF output ([`test.pdf`](https://github.com/chdemko/pandoc-latex-tip/files/2863106/test.pdf)), that was generated with

```
pandoc -F pandoc-latex-admonition -F pandoc-latex-tip -o test.pdf test.md
```

As you can see in the 2nd page of the PDF document, the icon is shown on the right side even if `position: left` was specified. On the 3rd page the icon is shown as expected.

I'm not an expert in LaTeX - but after some investigation it seems to be related to the two-sided layout of the document - as described [here](https://latexref.xyz/Marginal-notes.html):

>  If you are using one-sided layout (document option oneside) then it goes in the right margin. If you are using two-sided layout (document option twoside) then it goes in the outside margin. If you are in two-column layout (document option twocolumn) then it goes in the nearest margin. 

There are some workarounds discussed on several pages:

- [Marginpar on a fixed side of two-column double-sided memoir document](https://tex.stackexchange.com/questions/108981/marginpar-on-a-fixed-side-of-two-column-double-sided-memoir-document)
- [marginnote always on right side of the page](https://tex.stackexchange.com/questions/69595/marginnote-always-on-right-side-of-the-page)
- [How to control which side a margin paragraph appears on?](https://stackoverflow.com/questions/1358862/how-to-control-which-side-a-margin-paragraph-appears-on)

But due to my lack of understanding about LaTeX I wasn't able yet to fix the `pandoc-latex-tip` filter yet. Maybe you have an idea about this?

As a workaround I'm currently using the one-sided layout with the following lines in the YAML header of the markdown file:

```yaml
documentclass: book
classoption: oneside
```

But I would prefer to have a two-sided layout, in which the icons always appear on the left side. Any feedback, ideas and improvements on this are welcome. ;)

**Comment by chdemko** [comment]
I don't have this error here ([test.pdf](https://github.com/chdemko/pandoc-latex-tip/files/2866654/test.pdf)). Which version of LaTeX do you use and on which system (I'm on a ubuntu 18.04 using pdflatex)?

**Comment by pinhead84** [comment]
> I don't have this error here ([test.pdf](https://github.com/chdemko/pandoc-latex-tip/files/2866654/test.pdf)).

That's interesting.

> Which version of LaTeX do you use and on which system (I'm on a ubuntu 18.04 using pdflatex)?

I'm using Debian testing with its latest packages and their provided `texlive` packages.

```
$ pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.5
```

I've never specified a PDF engine in `pandoc`. According to the `pandoc` users manual, I guess that I also use `pdflatex` (as they call it their default engine):

```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian)
kpathsea version 6.3.1/dev
...
Compiled with libpng 1.6.34; using libpng 1.6.36
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.00
```

I assume, that Ubuntu 18.04 uses an older version of the [`texlive-latex-base` package](https://packages.ubuntu.com/bionic/texlive-latex-base) (that provides `pdflatex`) compared to the [`texlive-latex-base` package](https://packages.debian.org/buster/texlive-latex-base) in Debian testing. Maybe we're not on the same version and the problem was introduced with one of the last updates in `pdflatex`?

Out of curiosity I've tested my example on Debian stable. The problem does **not** occur here, too. Presumably Debian stable uses an older version of the [`texlive-latex-base` package](https://packages.debian.org/stretch/texlive-latex-base) compared to Ubuntu 18.04:

```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)
kpathsea version 6.2.2
...
Compiled with libpng 1.6.28; using libpng 1.6.28
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.48.0
```

To make a long story short: Maybe the same problem will also be introduced in future version of Ubuntu...

**Comment by chdemko** [comment]
Ok, I've found the issue: it's due to the marginnote package which is different. Ubuntu 18.04 uses 2017/04/22 v1.2b and if I take last version in the ctan package, I have your behavior.

File is /usr/share/texlive/texmf-dist/tex/latex/marginnote/marginnote.sty

**Comment by chdemko** [comment]
I have to think about this issue and decide a common behavior between pandoc-latex-tip and pandoc-latex-admonition

**Comment by pinhead84** [comment]
Thank you for looking into this. Can you give a short feedback here, if you found a conclusion about how you like to deal with this issue?

**Comment by chdemko** [comment]
This is solved in 2.0.3

**Comment by chdemko** [comment]
FYI, I've added an `inner` and an `outer` position for double sided document (they fallback to left and right for single-sided). This feature is in the 2.1.0 version. I will add the same feature in https://github.com/chdemko/pandoc-latex-admonition

**Comment by pinhead84** [comment]
Thank you for fixing this issue. In version 2.1.0 *pandoc-latex-tip* shows the icons as expected on a two sided layout with `position: left`. (Tested on Debian testing & stable.)
