### ISSUE TITLE
Icons are huge

### ISSUE THREAD

**Issue by geraldebberink** [chdemko/pandoc-latex-tip#12]
I have a problem with the icons being HUGE as you can see in [this file](https://github.com/chdemko/pandoc-latex-tip/files/3186664/latex-tip.pdf)

I am using 
Pandoc:
~~~
pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
~~~

PDFTEX:
~~~
pdftex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)
kpathsea version 6.3.1
Compiled with libpng 1.6.36; using libpng 1.6.36
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
~~~

The attached pdf is the result of processing:
~~~
pandoc pandoc-latex-tip-sample.txt -o output/latex-tip.pdf -f markdown --latex-engine=pdflatex --filter pandoc-latex-tip
~~~

Any pointers to a solution?

**Comment by chdemko** [comment]
Can you post your input files here. And try to update your pandoc version (current release is 2.7.2)

**Comment by geraldebberink** [comment]
The input version is the sample posted on [read the docs](https://raw.githubusercontent.com/chdemko/pandoc-latex-tip/master/docs/images/pandoc-latex-tip-sample.txt). 
Updating Pandoc is not as easy as it should working on it.

**Comment by geraldebberink** [comment]
Finally got Pandoc updated. (There were no less then 4 installs). And now everything is okay.
