### ISSUE TITLE
[Install] allow Pillow >= 3.0.0 

### ISSUE THREAD

**Issue by daamien** [chdemko/pandoc-latex-tip#6]
The installation process is kind of a mess because of a stange requirements in the egg package

If you take a look at the pip package here : https://pypi.python.org/packages/35/6c/5f98375df51f85ecab9268d3ff1f39caab8b1e620477ea530448016015ef/pandoc-latex-tip-1.0.1.tar.gz

and open it like that : ``tar xzvf pandoc-latex-tip-1.0.1.tar.gz``

Than look at the requirements:
```
$ grep pillow pandoc-latex-tip-1.0.1/pandoc_latex_tip.egg-info/requires.txt
pillow==3.0.0
```

This is strange because:

1- Pillow 3.0.0 is very hard to install  (see #1)
2- Pillow 4.0.0. is out and very simple to install
3- The ``setup.py`` file  says `pillow>=3.0.0` here https://github.com/chdemko/pandoc-latex-tip/blob/master/setup.py#L117

I can't find where the ``requires.txt`` comes from but I think that simply change `pillow==3.0.0` to `pillow>=3.0.0` would make the whole installation smoother

**Comment by daamien** [comment]
Same question for icon_font_to_png by he way ! 

The `requires.txt` file says  ``icon_font_to_png==0.3.4``

**Comment by chdemko** [comment]
I've already prepared the next version https://github.com/chdemko/pandoc-latex-tip/commit/dc575560be471ff4c9e945d5c6ed28cf8fc14e2e but I haven't yet published it

The requires.txt file is generated by python when the package is compiled. I will publish the new vrsion soon
